### PR TITLE
Home UI fixes and initiatives page

### LINKED ISSUE #195: Ui Fixes - Home
imagem

### PR DESCRIPTION
**Pull request by danidroid**
Closes #195 and #193 

- reduced Size box under the logo to 8
- Bump Size box to 16 below Slider
- Add click feedback on Stats red card
- Changed OverlayStatus Bar color on Android to Background White and Black text

- Initiatives change padding
- Initiatives change hit row size
- Initiatives change TextStyle for titles

✅ All tests passed
✅ dartfmt @ root

### CODE REVIEW

File: lib/resources/style/themes.dart [hunk 1]
```diff
@@ -56,12 +58,13 @@ class Themes {
...
       color: Colors.white,
       elevation: 0.0,
+      brightness: Platform.isAndroid ? Brightness.dark : Brightness.light,
       textTheme: defaultTextTheme,
       iconTheme: IconThemeData(
         color: Colors.black,
       ),
     ),
-    brightness: Brightness.light,
+    brightness: Platform.isAndroid ? Brightness.dark : Brightness.light,
```
Comment (OldMetalmind) [inline lib/resources/style/themes.dart]: Could you explain these lines, won't it cause problem in Android devices with darkmode?

Comment (danidroid) [reply lib/resources/style/themes.dart]: turning the dark mode on will not affect the Brightness, it will remain the same for both modes
