### PR TITLE
194 ui fixes statistics

### LINKED ISSUE #194: UI Fixes Statistics
imagem

The link for ESRI is:
https://bit.ly/APP2DGS

### PR DESCRIPTION
**Pull request by CodeGlitch**
My proposal this fix, replaces space with new line.
Also added a new line at the end of the first column, so that they would be aligned (includes logic in case switches to 2 words).
Added launURL for the ESRI text
Added license to some files
Moved import order on some files
Possibly closes #194

### CODE REVIEW

File: lib/ui/screens/statistics/statistics_page.dart [hunk 1]
```diff
@@ -124,7 +126,14 @@ class _StatisticsPageState extends BaseState<StatisticsPage, AppBloc> {
                           .textTheme
                           .display1
                           .copyWith(color: Covid19Colors.darkGrey),
-                      text: S.of(context).statisticsPageSuspects.toUpperCase(),
+                      text: S.of(context).statisticsPageSuspects.contains(" ")
+                          ? S
+                              .of(context)
```
Comment (danidroid) [inline lib/ui/screens/statistics/statistics_page.dart]:
```suggestion
                             "${S.of(context).statisticsPageSuspects.toUpperCase()}$newLine"
```
